// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVtXMFo9arVyt0EbH0ONAu4rOIZoqe20U',
    appId: '1:1029565748798:web:fedb055b4d377123bfa36f',
    messagingSenderId: '1029565748798',
    projectId: 'homely-9a631',
    authDomain: 'homely-9a631.firebaseapp.com',
    storageBucket: 'homely-9a631.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3DCUKgghuBnRldWAeZpU35oAf6FBl0U',
    appId: '1:1029565748798:android:fedb055b4d377123bfa36f',
    messagingSenderId: '1029565748798',
    projectId: 'homely-9a631',
    storageBucket: 'homely-9a631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtXMFo9arVyt0EbH0ONAu4rOIZoqe20U',
    appId: '1:1029565748798:ios:402345378cf2ae50bfa36f',
    messagingSenderId: '1029565748798',
    projectId: 'homely-9a631',
    storageBucket: 'homely-9a631.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1homely2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtXMFo9arVyt0EbH0ONAu4rOIZoqe20U',
    appId: '1:1029565748798:macos:402345378cf2ae50bfa36f',
    messagingSenderId: '1029565748798',
    projectId: 'homely-9a631',
    storageBucket: 'homely-9a631.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1homely2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVtXMFo9arVyt0EbH0ONAu4rOIZoqe20U',
    appId: '1:1029565748798:windows:fedb055b4d377123bfa36f',
    messagingSenderId: '1029565748798',
    projectId: 'homely-9a631',
    storageBucket: 'homely-9a631.firebasestorage.app',
  );
}

